package com.QA.locators;

public class CommonLocators {

    public static final String Login_Champ_Username = "username";
    public static final String Login_Champ_password = "password";
    public static final String Login_Bouton_connexion = "/html/body/app-root/ng-component/div/div/div/div/div/acc-login-authentication/div/div/form/button";
    public static final String Bouton_Role_RH = "/html/body/app-root/app-layout/div/app-header/nav/div[2]/ul[1]/li[2]/a/em";
    public static final String Bouton_Menu_Etendu = "/html/body/app-root/app-layout/div/app-header/nav/div[2]/ul[1]/li[1]/a[1]/em";
    public static final String Bouton_Module_Connect = "/html/body/app-root/app-layout/div/app-sidebar/nav/ul/li[6]/a";
    public static final String Notification_Simple = "div[class='sn-content']";
    public static final String Core_RH = "/html/body/app-root/app-layout/div/app-sidebar/nav/ul/li[3]";
    public static final String Bouton_Annonce="/html/body/app-root/app-layout/div/app-sidebar/nav/ul/li[6]/ul/li[6]/a";
    public static final String Bouton_Portal = "/html/body/app-root/app-layout/div/app-header/nav/div[2]/ul[1]/li[2]/a/em";
    public static final String Option_Liste_Profil_Tag = "li[class='ql-mention-list-item selected']";
    public static final String Mon_Equipe ="/html/body/app-root/app-layout/div/section/div/acc-global-container/acc-portal-container/div/div/div[1]/acc-left-side-container/div/acc-user-widget/div/div[3]/ul/li[2]";
    public static final String Icone_Nom_Utilisateur="/html/body/app-root/app-layout/div/section/div/acc-global-container/acc-portal-container/div/div/div[1]/acc-left-side-container/div/acc-user-widget/div/div[2]/span/span";
    public static final String Module_Easyrun = "/html/body/app-root/app-layout/div/app-sidebar/nav/ul/li[4]";
    public static final String Première_Notification_Portal = "/html/body/app-root/app-layout/div/app-header/nav/div[2]/ul[2]/li[2]/div/notification/div[1]/div[1]";
    public static final String Bouton_Notifications_Portal = "//*[@id=\"dropdownManual\"]/em";
    public static final String Module_Administration = "/html/body/app-root/app-layout/div/app-sidebar/nav/ul/li[7]";
    public static final String Sous_Module_Gestion_des_calendriers = "/html/body/app-root/app-layout/div/app-sidebar/nav/ul/li[7]/ul/li[5]";
    public static final String Onglet_Journée_type = "/html/body/app-root/app-layout/div/section/div/ng-component/div/ul/li/ul/li[2]";
    public static final String Bouton_Ajouter_Journée_type = "/html/body/app-root/app-layout/div/section/div/ng-component/div/div/acc-absence-day-type-setting-component/div/button";
    public static final String Code_Ajout_Journée_type = "//*[@id=\"popup\"]/div/section/div[2]/div[1]/input";
    public static final String Libellé_Ajout_Journée_type = "//*[@id=\"popup\"]/div/section/div[2]/div[2]/input";
    public static final String Type_Ajout_Journée_type = "//*[@id=\"popup\"]/div/section/div[3]/div[1]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Type_Ajout_Journée_type_IL = "//*[@id=\"popup\"]/div/section/div[3]/div[1]/acc-select-cr/ng-select/div/input";
    public static final String Type_Ajout_Journée_type_CL = "//*[@id=\"popup\"]/div/section/div[3]/div[1]/acc-select-cr/ng-select/div/ul/li[1]";
    public static final String Nombre_Heures_Ajout_Journée_Type = "//*[@id=\"popup\"]/div/section/div[4]/div/ngb-timepicker/fieldset/div/div[1]/input";
    public static final String Nombre_Minutes_Ajout_Journée_Type = "//*[@id=\"popup\"]/div/section/div[4]/div/ngb-timepicker/fieldset/div/div[3]/input";
    public static final String Statut_Ajout_Journée_Type = "//*[@id=\"popup\"]/div/section/div[7]/div/div/label/input";
    public static final String Bouton_Valider_Ajout_Journée_type = "//*[@id=\"popup\"]/div/div/button[2]";
    public static final String Onglet_Semaine_type = "/html/body/app-root/app-layout/div/section/div/ng-component/div/ul/li/ul/li[3]/a";
    public static final String Bouton_Ajouter_Semaine_type = "/html/body/app-root/app-layout/div/section/div/ng-component/div/div/absence-weeks-setting-component/div[1]/button";
    public static final String Code_Ajout_Semaine_type = "/html/body/app-root/app-layout/div/section/div/ng-component/div/div/absence-weeks-setting-component/acc-week-add-new-popup/form/div/div/section/div[2]/div[1]/input";
    public static final String Libellé_Ajout_Semaine_type = "/html/body/app-root/app-layout/div/section/div/ng-component/div/div/absence-weeks-setting-component/acc-week-add-new-popup/form/div/div/section/div[2]/div[2]/input";
    public static final String Case_Samedi_Ajout_Semaine_Type = "/html/body/app-root/app-layout/div/section/div/ng-component/div/div/absence-weeks-setting-component/acc-week-add-new-popup/form/div/div/section/div[2]/div[3]/table/tbody/tr[1]/td[6]/div/label/span";
    public static final String Case_Dimanche_Ajout_Semaine_Type = "/html/body/app-root/app-layout/div/section/div/ng-component/div/div/absence-weeks-setting-component/acc-week-add-new-popup/form/div/div/section/div[2]/div[3]/table/tbody/tr[1]/td[7]/div/label/span";
    public static final String Jour_ouvrable_Ajout_Semaine_Type = "/html/body/app-root/app-layout/div/section/div/ng-component/div/div/absence-weeks-setting-component/acc-week-add-new-popup/form/div/div/section/div[2]/div[4]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Jour_ouvrable_Ajout_Semaine_Type_IL = "/html/body/app-root/app-layout/div/section/div/ng-component/div/div/absence-weeks-setting-component/acc-week-add-new-popup/form/div/div/section/div[2]/div[4]/acc-select-cr/ng-select/div/input";
    public static final String Jour_ouvrable_Ajout_Semaine_Type_CL = "/html/body/app-root/app-layout/div/section/div/ng-component/div/div/absence-weeks-setting-component/acc-week-add-new-popup/form/div/div/section/div[2]/div[4]/acc-select-cr/ng-select/div/ul/li";
    public static final String Bouton_Valider_Ajout_Semaine_type = "/html/body/app-root/app-layout/div/section/div/ng-component/div/div/absence-weeks-setting-component/acc-week-add-new-popup/form/div/div/div/button[2]";
    public static final String Onglet_Cycles_de_travail = "/html/body/app-root/app-layout/div/section/div/ng-component/div/ul/li/ul/li[4]";
    public static final String Bouton_Ajouter_Cycles_de_travail = "/html/body/app-root/app-layout/div/section/div/ng-component/div/div/acc-absence-cycle-setting-component/div/button";
    public static final String Code_Ajout_Cycle_de_travail = "//*[@id=\"popup\"]/div/section/div[2]/div[1]/input";
    public static final String Libellé_Ajout_Cycle_de_travail = "//*[@id=\"popup\"]/div/section/div[2]/div[2]/input";
    public static final String Statut_Ajout_Cycle_De_Travail = "//*[@id=\"popup\"]/div/section/div[3]/div/div/label/input";
    public static final String Semaines_types_Ajout_Cycle_de_travail = "//*[@id=\"popup\"]/div/section/div[4]/div/ul[1]/li";
    public static final String Bouton_Valider_Ajout_Cycle_de_travail = "//*[@id=\"popup\"]/div/div/button[2]";
    public static final String Bouton_Affectation_Population_Cycles_de_travail = "/html/body/app-root/app-layout/div/section/div/ng-component/div/div/acc-absence-cycle-setting-component/acc-absence-cycle-list/div/p-datatable/div/div[1]/table/tbody/tr[1]/td[5]/span[2]/span/i[3]";
    public static final String Bouton_Ajout_Affectation_Population_Cycle_de_travail = "/html/body/ngb-modal-window/div/div/acc-absence-affectations-assignment/div/header/a[2]";
    public static final String Date_d_effet_Affectation_Population_Cycle_de_travail = "/html/body/ngb-modal-window/div/div/acc-absence-affectations-assignment/div/form/section/div/div[1]/acc-date-picker/my-date-picker/div/div/input";
    public static final String Premiere_semaine_Affectation_Popultaion_Cycle_de_travail = "/html/body/ngb-modal-window/div/div/acc-absence-affectations-assignment/div/form/section/div/div[2]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Premiere_semaine_Affectation_Popultaion_Cycle_de_travail_IL = "/html/body/ngb-modal-window/div/div/acc-absence-affectations-assignment/div/form/section/div/div[2]/acc-select-cr/ng-select/div/input";
    public static final String Premiere_semaine_Affectation_Popultaion_Cycle_de_travail_CL = "/html/body/ngb-modal-window/div/div/acc-absence-affectations-assignment/div/form/section/div/div[2]/acc-select-cr/ng-select/div/ul/li";
    public static final String Population_Affectation_Population_Cycle_de_travail = "/html/body/ngb-modal-window/div/div/acc-absence-affectations-assignment/div/form/section/div/div[3]/acc-select-population/div/div[1]/input";
    public static final String Valider_Affectation_Population_Cycle_de_travail = "/html/body/ngb-modal-window/div/div/acc-absence-affectations-assignment/div/header/a[2]";
    public static final String Bouton_Enquete="/html/body/app-root/app-layout/div/app-sidebar/nav/ul/li[6]/ul/li[3]";
    public static final String Premier_User_Nom_Notification="/html/body/app-root/app-layout/div/app-header/nav/div[2]/ul[2]/li[2]/div/notification/div[1]/div[1]/a/div/div[2]/div[1]/span[1]";
    public static final String Compteur_Notification="/html/body/app-root/app-layout/div/app-header/nav/div[2]/ul[2]/li[2]/a/div";
    public static final String  Liste_Notifications="div[class='notification-container col-md-12 col-sm-12 p0']";
    public static final String Sous_module_Configuration_Talent="a[href='/hr-space/talent/configuration']";
    public static final String Module_Talent="a[title='Talent']";
    public static final String Bouton_Lien_Utile="/html/body/app-root/app-layout/div/app-sidebar/nav/ul/li[6]/ul/li[4]";
    public static final String Bouton_Administration="a[title='Administration']";
    public static final String Bouton_Configuration_Systeme="a[href='/hr-space/administration/system-config']";
    public static final String Bouton_Autres_Parametres="/html/body/app-root/app-layout/div/section/div/app-system-config-container/div/div/div[1]/system-config-list/div/div[2]/a[6]";
    public static final String Bouton_Autres_Parametres_Enregistrer="/html/body/app-root/app-layout/div/section/div/app-system-config-container/div/div/div[2]/app-system-config/echelon-config/div/div[2]/div/form/div/div/button[2]";
    public static final String Bouton_Configuration="em[title='Configuration']";
    public static final String Bouton_Profil="a[href='#profileConfig']";

}
