package com.QA.locators;

public class ConfiguartionCoreRHLocators {

    public static final String Configuration_Core_RH = "/html[1]/body[1]/app-root[1]/app-layout[1]/div[1]/app-sidebar[1]/nav[1]/ul[1]/li[3]/ul[1]/li[5]/a[1]";
    public static final String Liste_Collections = "/html[1]/body[1]/app-root[1]/app-layout[1]/div[1]/section[1]/div[1]/acc-core-config-container[1]/div[1]/div[2]/acc-generic-cr-container[1]/div[1]/div[2]/div[1]/div[2]/app-acc-list[1]/div[1]/div[1]/a";
    public static final String Liste_Configuration = "/html[1]/body[1]/app-root[1]/app-layout[1]/div[1]/section[1]/div[1]/acc-core-config-container[1]/div[1]/div[1]/div[1]/div[2]/a";
    public static final String Code_Marque = "input[class*='ng-valid'][formcontrolname='code']";
    public static final String Marque = "input[class*='ng-valid'][formcontrolname='label']";
    public static final String Bouton_Ajout_Marque = "//*[@id=\"fields\"]/div/form/div/div[9]/div/div/div[3]/span";
    public static final String Bouton_Enregistrer_Marque = "/html[1]/body[1]/app-root[1]/app-layout[1]/div[1]/section[1]/div[1]/acc-core-config-container[1]/div[1]/div[2]/acc-generic-cr-container[1]/div[1]/div[2]/div[1]/div[1]/div[2]/acc-header-revert-save[1]/div[1]/a[1]/i[1]";
    public static final String Recherche_Collection = "/html[1]/body[1]/app-root[1]/app-layout[1]/div[1]/section[1]/div[1]/acc-core-config-container[1]/div[1]/div[2]/acc-generic-cr-container[1]/div[1]/div[2]/div[1]/div[1]/div[1]/div[1]/input[1]";
    public static final String Bouton_Ajouter_Modèle = "/html[1]/body[1]/app-root[1]/app-layout[1]/div[1]/section[1]/div[1]/acc-core-config-container[1]/div[1]/div[2]/acc-generic-cr-container[1]/div[1]/div[2]/div[1]/div[2]/div[1]/acc-vehiclemodel-container[1]/div[2]/section[1]/div[2]/acc-tab-header[1]/header[1]/ul[1]/li[2]/a[1]";
    public static final String Code_Modèle = "/html[1]/body[1]/app-root[1]/app-layout[1]/div[1]/section[1]/div[1]/acc-core-config-container[1]/div[1]/div[2]/acc-generic-cr-container[1]/div[1]/div[2]/div[1]/div[2]/div[1]/acc-vehiclemodel-container[1]/div[2]/section[1]/div[2]/div[1]/div[2]/vehiclemodel-form[1]/div[1]/form[1]/div[1]/div[1]/input[1]";
    public static final String Libellé_Modèle = "/html[1]/body[1]/app-root[1]/app-layout[1]/div[1]/section[1]/div[1]/acc-core-config-container[1]/div[1]/div[2]/acc-generic-cr-container[1]/div[1]/div[2]/div[1]/div[2]/div[1]/acc-vehiclemodel-container[1]/div[2]/section[1]/div[2]/div[1]/div[2]/vehiclemodel-form[1]/div[1]/form[1]/div[1]/div[2]/input[1]";
    public static final String Liste_Marques = "/html[1]/body[1]/app-root[1]/app-layout[1]/div[1]/section[1]/div[1]/acc-core-config-container[1]/div[1]/div[2]/acc-generic-cr-container[1]/div[1]/div[2]/div[1]/div[2]/div[1]/acc-vehiclemodel-container[1]/div[2]/section[1]/div[2]/div[1]/div[2]/vehiclemodel-form[1]/div[1]/form[1]/div[1]/div[3]/acc-select-cr[1]/ng-select[1]/div[1]/div[2]/span[1]";
    public static final String Liste_Marques_IL = "/html[1]/body[1]/app-root[1]/app-layout[1]/div[1]/section[1]/div[1]/acc-core-config-container[1]/div[1]/div[2]/acc-generic-cr-container[1]/div[1]/div[2]/div[1]/div[2]/div[1]/acc-vehiclemodel-container[1]/div[2]/section[1]/div[2]/div[1]/div[2]/vehiclemodel-form[1]/div[1]/form[1]/div[1]/div[3]/acc-select-cr[1]/ng-select[1]/div[1]/input[1]";
    public static final String Liste_Marques_CL = "/html[1]/body[1]/app-root[1]/app-layout[1]/div[1]/section[1]/div[1]/acc-core-config-container[1]/div[1]/div[2]/acc-generic-cr-container[1]/div[1]/div[2]/div[1]/div[2]/div[1]/acc-vehiclemodel-container[1]/div[2]/section[1]/div[2]/div[1]/div[2]/vehiclemodel-form[1]/div[1]/form[1]/div[1]/div[3]/acc-select-cr[1]/ng-select[1]/div[1]/ul/li";
    public static final String Bouton_Valider_Modèle = "/html[1]/body[1]/app-root[1]/app-layout[1]/div[1]/section[1]/div[1]/acc-core-config-container[1]/div[1]/div[2]/acc-generic-cr-container[1]/div[1]/div[2]/div[1]/div[2]/div[1]/acc-vehiclemodel-container[1]/div[2]/section[1]/div[2]/div[1]/div[2]/vehiclemodel-form[1]/div[1]/form[1]/div[2]/button[2]";
    public static final String Bouton_Enregistrer_Modéle = "/html/body/app-root/app-layout/div/section/div/acc-core-config-container/div/div[2]/acc-generic-cr-container/div/div[2]/div/div[2]/div/acc-vehiclemodel-container/div[2]/acc-header-revert-save/div/a[1]/i";
}
