package com.QA.locators;

public class ConfigurationTalentLocators {

   public static final String Classification_conf = "span[title='Classification']";
   public static final String Ajouter_classification = "a[class='buttonAdd']";
   public static final String Libelle_Classif_ajout = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-classification-form/div/form/div[1]/div[1]/input";
   public static final String Classification_parent = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-classification-form/div/form/div[1]/div[2]/acc-select-cr/ng-select/div/div[2]/span";
   public static final String Classification_parent_IL = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-classification-form/div/form/div[1]/div[2]/acc-select-cr/ng-select/div/input";
   public static final String Classification_parent_CL = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-classification-form/div/form/div[1]/div[2]/acc-select-cr/ng-select/div/ul/li";
   public static final String Chiffre_ajout_classification = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-classification-form/div/form/div[2]/div[1]/acc-select-cr/ng-select/div/div[2]/span";
   public static final String Chiffre_ajout_classification_IL = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-classification-form/div/form/div[2]/div[1]/acc-select-cr/ng-select/div/input";
   public static final String Chiffre_ajout_classification_CL = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-classification-form/div/form/div[2]/div[1]/acc-select-cr/ng-select/div/ul/li";
   public static final String Coefficient_ajout_classification = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-classification-form/div/form/div[2]/div[2]/acc-select-cr/ng-select/div/div[2]/span";
   public static final String Coefficient_ajout_classification_IL = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-classification-form/div/form/div[1]/div[2]/acc-select-cr/ng-select/div/input";
   public static final String Coefficient_ajout_classification_CL = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-classification-form/div/form/div[2]/div[2]/acc-select-cr/ng-select/div/ul/li";
   public static final String Valider_ajout_classification = "button[class='mb-sm btn btn-info btn-outline']";
   public static final String Sauvegarder_classification = "i[class='action-buttons icons8 icons8-save-as pull-right clickable']";
   public static final String Derniere_Classification_Affichee_Libelle = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[1]/acc-evaluation-configuration-classification-table/table/tbody/tr[10]/td[1]";
   public static final String Derniere_Classification_Affichee_ClassificationParent = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[1]/acc-evaluation-configuration-classification-table/table/tbody/tr[10]/td[2]";
   public static final String Derniere_Classification_Affichee_Echelle = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[1]/acc-evaluation-configuration-classification-table/table/tbody/tr[10]/td[3]";
   public static final String Option_conf_classification = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[1]/acc-evaluation-configuration-classification-table/table/tbody/tr[10]/td[4]/div/a";
   public static final String Editer_option_conf_classification = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[1]/acc-evaluation-configuration-classification-table/table/tbody/tr[10]/td[4]/div/ul/li[1]";
   public static final String Liste_Calification_Configuration_Talent = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[1]/acc-evaluation-configuration-classification-table/table/tbody/tr";
   public static final String Supprimer_option_conf_classification = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[1]/acc-evaluation-configuration-classification-table/table/tbody/tr[10]/td[4]/div/ul/li[2]";
   public static final String Bouton_Formations_Talent = "//*[@id=\"menu-config-1-header\"]/a";
   public static final String Bouton_Formations_Thematique_Talent = "//*[@id=\"menu-config-1\"]/div/a[1]";
   public static final String Ajout_occurrence_thematique_conf = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-single-element-generic-cr-container/div[2]/div/section/div[2]/form/div/div[10]/div/div/input[2]";
   public static final String Ajouter_thematique_conf = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-single-element-generic-cr-container/div[2]/div/section/div[2]/form/div/div[10]/div/div/span";
   public static final String Sauvegarder_thematique = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-single-element-generic-cr-container/div[2]/div/acc-header-revert-save/div/a[1]/i";
   public static final String Supprimer_Test_Ajout_thematique_Formation = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-single-element-generic-cr-container/div[2]/div/section/div[2]/form/div/div[10]/div/div/span/button";
   public static final String Liste_Thematique_Formation = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-single-element-generic-cr-container/div[2]/div/section/div[2]/form/div/div";
   public static final String Liste_Nombre_Classification_Afficher = "small[class='text-muted inline']";
   public static final String Bouton_Pagination_Competence_Classification="a[aria-label='»']";

}