package com.QA.locators;

public class ConfigurationTalentLocators {

   public static final String Classification_conf = "span[title='Classification']";
   public static final String Ajouter_classification = "a[class='buttonAdd']";
   public static final String Libelle_Classif_ajout = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-classification-form/div/form/div[1]/div[1]/input";
   public static final String Classification_parent = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-classification-form/div/form/div[1]/div[2]/acc-select-cr/ng-select/div/div[2]/span";
   public static final String Classification_parent_IL = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-classification-form/div/form/div[1]/div[2]/acc-select-cr/ng-select/div/input";
   public static final String Classification_parent_CL = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-classification-form/div/form/div[1]/div[2]/acc-select-cr/ng-select/div/ul/li";
   public static final String Chiffre_ajout_classification = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-classification-form/div/form/div[2]/div[1]/acc-select-cr/ng-select/div/div[2]/span";
   public static final String Chiffre_ajout_classification_IL = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-classification-form/div/form/div[2]/div[1]/acc-select-cr/ng-select/div/input";
   public static final String Chiffre_ajout_classification_CL = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-classification-form/div/form/div[2]/div[1]/acc-select-cr/ng-select/div/ul/li";
   public static final String Coefficient_ajout_classification = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-classification-form/div/form/div[2]/div[2]/acc-select-cr/ng-select/div/div[2]/span";
   public static final String Coefficient_ajout_classification_IL = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-classification-form/div/form/div[1]/div[2]/acc-select-cr/ng-select/div/input";
   public static final String Coefficient_ajout_classification_CL = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-classification-form/div/form/div[2]/div[2]/acc-select-cr/ng-select/div/ul/li";
   public static final String Valider_ajout_classification = "button[class='mb-sm btn btn-info btn-outline']";
   public static final String Sauvegarder_classification = "i[class='action-buttons icons8 icons8-save-as pull-right clickable']";
   public static final String Derniere_Classification_Affichee_Libelle = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[1]/acc-evaluation-configuration-classification-table/table/tbody/tr[10]/td[1]";
   public static final String Derniere_Classification_Affichee_ClassificationParent = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[1]/acc-evaluation-configuration-classification-table/table/tbody/tr[10]/td[2]";
   public static final String Derniere_Classification_Affichee_Echelle = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[1]/acc-evaluation-configuration-classification-table/table/tbody/tr[10]/td[3]";
   public static final String Option_conf_classification = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[1]/acc-evaluation-configuration-classification-table/table/tbody/tr[10]/td[4]/div/a";
   public static final String Editer_option_conf_classification = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[1]/acc-evaluation-configuration-classification-table/table/tbody/tr[10]/td[4]/div/ul/li[1]";
   public static final String Liste_Calification_Configuration_Talent = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[1]/acc-evaluation-configuration-classification-table/table/tbody/tr";
   public static final String Supprimer_option_conf_classification = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-classication/div[2]/section/div[2]/div/div[1]/acc-evaluation-configuration-classification-table/table/tbody/tr[10]/td[4]/div/ul/li[2]";
   public static final String Bouton_Formations_Talent = "//*[@id=\"menu-config-1-header\"]/a";
   public static final String Bouton_Formations_Thematique_Talent = "//*[@id=\"menu-config-1\"]/div/a[1]";
   public static final String Ajout_occurrence_thematique_conf = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-single-element-generic-cr-container/div[2]/div/section/div[2]/form/div/div[10]/div/div/input[2]";
   public static final String Ajouter_thematique_conf = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-single-element-generic-cr-container/div[2]/div/section/div[2]/form/div/div[10]/div/div/span";
   public static final String Sauvegarder_thematique = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-single-element-generic-cr-container/div[2]/div/acc-header-revert-save/div/a[1]/i";
   public static final String Supprimer_Test_Ajout_thematique_Formation = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-single-element-generic-cr-container/div[2]/div/section/div[2]/form/div/div[10]/div/div/span/button";
   public static final String Liste_Thematique_Formation = "/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-single-element-generic-cr-container/div[2]/div/section/div[2]/form/div/div";
   public static final String Liste_Nombre_Classification_Afficher = "small[class='text-muted inline']";
   public static final String Bouton_Pagination_Competence_Classification="a[aria-label='»']";
   public static final String Bouton_Evaluation_Talent="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[1]/acc-evaluation-configuration-selection-list/ngb-accordion/div/div/a";
   public static final String Bouton_Evaluation_Axe_Talent="span[title='Axes']";
   public static final String Ajouter_Axe_Evaluation="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-axis/div[2]/div/section/div[2]/acc-tab-header/header/ul/li[2]/a";
   public static final String Libelle_Ajout_Axe="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-axis/div[2]/div/section/div[2]/div/div[2]/acc-evaluation-configuration-axis-form/div/form/div[1]/div/input";
   public static final String Valider_Ajout_Axe="button[class='mb-sm btn btn-info btn-outline']";
   public static final String Sauvegarder_Ajout_Axe="i[class='action-buttons icons8 icons8-save-as pull-right clickable']";
   public static final String Liste_Nombre_Axe_Afficher="small[class='text-muted inline']";
   public static final String Liste_Axe_Talent="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-axis/div[2]/div/section/div[2]/div/div[1]/acc-evaluation-configuration-axis-table/table/tbody/tr";
   public static final String Libelle_Ajout_Axe_Option="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-axis/div[2]/div/section/div[2]/div/div[2]/acc-evaluation-configuration-axis-form/div/form/div[1]/div/input";
   public static final String Bouton_Evaluation_Obj_Strategique_Talent="span[title='Objectifs stratégiques']";
   public static final String Ajouter_Obj_Strategique_Evaluation="a[class='buttonAdd']";
   public static final String Libelle_Ajout_Obj_strategique="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-strategictarget/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-strategictarget-form/div/form/div[1]/div[1]/input";
   public static final String Description_Ajout_Obj_strategique="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-strategictarget/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-strategictarget-form/div/form/div[1]/div[2]/input";
   public static final String Valider_Ajout_Obj_strategique="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-strategictarget/div[2]/section/div[2]/div/div[2]/acc-evaluation-configuration-strategictarget-form/div/form/div[2]/button[2]";
   public static final String Sauvegarder_Ajout_Obj_strategique="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-strategictarget/div[2]/acc-header-revert-save/div/a[1]/i";
   public static final String Liste_Nombre_ObjectifStrategique_Afficher="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-strategictarget/div[2]/section/div[2]/div/div[1]/acc-evaluation-configuration-strategictarget-table/footer/div/div/small";
   public static final String Bouton_Pagination_Objectif_Strategique="a[aria-label='»']";
   public static final String List_Objectif_Stategique="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-strategictarget/div[2]/section/div[2]/div/div[1]/acc-evaluation-configuration-strategictarget-table/table/tbody/tr";
   public static final String Bouton_Evaluation_Obj_commun_Talent="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[1]/acc-evaluation-configuration-selection-list/ngb-accordion/div/div[2]/div/a[3]/span";
   public static final String Ajouter_Obj_commun_Evaluation="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-communtarget/div[2]/div/section/div[2]/acc-tab-header/header/ul/li[2]/a";
   public static final String Libelle_Ajout_Obj_commun="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-communtarget/div[2]/div/section/div[2]/div/div[2]/acc-evaluation-configuration-communtarget-form/div/form/div[1]/div[1]/input";
   public static final String Description_Ajout_Obj_commun="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-communtarget/div[2]/div/section/div[2]/div/div[2]/acc-evaluation-configuration-communtarget-form/div/form/div[1]/div[3]/textarea";
   public static final String Libelle1_Ajout_Obj_commun="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-communtarget/div[2]/div/section/div[2]/div/div[2]/acc-evaluation-configuration-communtarget-form/div/form/div[2]/div[2]/div/div/div/div[1]/input";
   public static final String Valeur_cible1_Ajout_Obj_commun="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-communtarget/div[2]/div/section/div[2]/div/div[2]/acc-evaluation-configuration-communtarget-form/div/form/div[2]/div[2]/div/div/div/div[2]/input";
   public static final String Axe_Ajout_Obj_commun="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-communtarget/div[2]/div/section/div[2]/div/div[2]/acc-evaluation-configuration-communtarget-form/div/form/div[1]/div[2]/acc-select-cr/ng-select/div/div[2]/span";
   public static final String Axe_Ajout_Obj_commun_IL="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-communtarget/div[2]/div/section/div[2]/div/div[2]/acc-evaluation-configuration-communtarget-form/div/form/div[1]/div[2]/acc-select-cr/ng-select/div/input";
   public static final String Axe_Ajout_Obj_commun_CL="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-communtarget/div[2]/div/section/div[2]/div/div[2]/acc-evaluation-configuration-communtarget-form/div/form/div[1]/div[2]/acc-select-cr/ng-select/div/ul/li";
   public static final String Valider_Ajout_Obj_commun="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-communtarget/div[2]/div/section/div[2]/div/div[2]/acc-evaluation-configuration-communtarget-form/div/form/div[3]/div/button[2]";
   public static final String Sauvegarder_Ajout_Obj_commun="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-communtarget/div[2]/div/acc-header-revert-save/div/a[1]/i";
   public static final String Bouton_Pagination_Objectif_Commun="a[aria-label='»']";
   public static final String List_Objectif_Commun="/html/body/app-root/app-layout/div/section/div/acc-hr-talent-component/acc-hr-talent-configuration/div[2]/div[2]/section/acc-evaluation-configuration-communtarget/div[2]/div/section/div[2]/div/div[1]/acc-evaluation-configuration-communtarget-table/table/tbody/tr";




}