package com.QA.locators;

public class GestionDuPersonnel {

    public static final String Gestion_du_personnel = "/html/body/app-root/app-layout/div/app-sidebar/nav/ul/li[3]/ul/li[3]";
    public static final String Ajouter_collaborateur = "/html/body/app-root/app-layout/div/section/div/ng-component/header/acc-core-rh-referential-add-delete-actions/i[2]";
    public static final String Date_d_entrée_collaborateur = "//*[@id=\"formStep1\"]/div[1]/div[1]/acc-date-picker/my-date-picker/div/div/input";
    public static final String Type_collaborateur = "//*[@id=\"formStep1\"]/div[1]/div[2]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Type_collaborateur_IL = "//*[@id=\"formStep1\"]/div[1]/div[2]/acc-select-cr/ng-select/div/input";
    public static final String Type_collaborateur_CL = "//*[@id=\"formStep1\"]/div[1]/div[2]/acc-select-cr/ng-select/div/ul/li";
    public static final String Matricule_collaborateur = "//*[@id=\"formStep1\"]/div[1]/div[3]/input";
    public static final String Qualité_collaborateur = "//*[@id=\"formStep1\"]/div[2]/div[1]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Qualité_collaborateur_IL = "//*[@id=\"formStep1\"]/div[2]/div[1]/acc-select-cr/ng-select/div/input";
    public static final String Qualité_collaborateur_CL = "//*[@id=\"formStep1\"]/div[2]/div[1]/acc-select-cr/ng-select/div/ul/li";
    public static final String Nom_collaborateur = "lastName";
    public static final String Prénom_collaborateur = "firstName";
    public static final String Date_de_naissance_collaborateur = "//*[@id=\"formStep1\"]/div[3]/div[1]/acc-date-picker/my-date-picker/div/div/input";
    public static final String Pays_de_naissance_collaborateur = "//*[@id=\"formStep1\"]/div[3]/div[2]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Pays_de_naissance_collaborateur_IL = "//*[@id=\"formStep1\"]/div[3]/div[2]/acc-select-cr/ng-select/div/input";
    public static final String Pays_de_naissance_collaborateur_CL = "//*[@id=\"formStep1\"]/div[3]/div[2]/acc-select-cr/ng-select/div/ul/li";
    public static final String Situation_familiale_collaborateur = "//*[@id=\"formStep1\"]/div[3]/div[3]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Situation_familiale_collaborateur_IL = "//*[@id=\"formStep1\"]/div[3]/div[3]/acc-select-cr/ng-select/div/input";
    public static final String Situation_familiale_collaborateur_CL = "//*[@id=\"formStep1\"]/div[3]/div[3]/acc-select-cr/ng-select/div/ul/li";
    public static final String Continuer = "//*[@id=\"step1\"]/div/acc-app-core-rh-employee-add-popup-identification/ul/li/button";
    public static final String Motif_d_entrée_collaborateur = "//*[@id=\"formStep2\"]/div[1]/div[1]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Motif_d_entrée_collaborateur_IL = "//*[@id=\"formStep2\"]/div[1]/div[1]/acc-select-cr/ng-select/div/input";
    public static final String Motif_d_entrée_collaborateur_CL = "//*[@id=\"formStep2\"]/div[1]/div[1]/acc-select-cr/ng-select/div/ul/li";
    public static final String Société_collaborateur = "//*[@id=\"formStep2\"]/div[1]/div[2]/acc-select-list/ng-select/div/div[2]/span";
    public static final String Société_collaborateur_IL = "//*[@id=\"formStep2\"]/div[1]/div[2]/acc-select-list/ng-select/div/input";
    public static final String Société_collaborateur_CL = "//*[@id=\"formStep2\"]/div[1]/div[2]/acc-select-list/ng-select/div/ul/li";
    public static final String Etablissement_collaborateur = "//*[@id=\"formStep2\"]/div[1]/div[3]/acc-select-list/ng-select/div/div[2]/span";
    public static final String Etablissement_collaborateur_IL = "//*[@id=\"formStep2\"]/div[1]/div[3]/acc-select-list/ng-select/div/input";
    public static final String Etablissement_collaborateur_CL = "//*[@id=\"formStep2\"]/div[1]/div[3]/acc-select-list/ng-select/div/ul/li";
    public static final String Entité_organisationnelle_collaborateur = "//*[@id=\"formStep2\"]/div[2]/div[1]/acc-select-list/ng-select/div/div[2]/span";
    public static final String Entité_organisationnelle_collaborateur_IL = "//*[@id=\"formStep2\"]/div[2]/div[1]/acc-select-list/ng-select/div/input";
    public static final String Entité_organisationnelle_collaborateur_CL = "//*[@id=\"formStep2\"]/div[2]/div[1]/acc-select-list/ng-select/div/ul/li";
    public static final String Emploi_collaborateur = "//*[@id=\"formStep2\"]/div[2]/div[2]/acc-select-list/ng-select/div/div[2]/span";
    public static final String Emploi_collaborateur_IL = "//*[@id=\"formStep2\"]/div[2]/div[2]/acc-select-list/ng-select/div/input";
    public static final String Emploi_collaborateur_CL = "//*[@id=\"formStep2\"]/div[2]/div[2]/acc-select-list/ng-select/div/ul/li";
    public static final String Poste_collaborateur = "//*[@id=\"formStep2\"]/div[2]/div[3]/acc-select-list/ng-select/div/div[2]/span";
    public static final String Poste_collaborateur_IL = "//*[@id=\"formStep2\"]/div[2]/div[3]/acc-select-list/ng-select/div/input";
    public static final String Poste_collaborateur_CL = "//*[@id=\"formStep2\"]/div[2]/div[3]/acc-select-list/ng-select/div/ul/li";
    public static final String Type_du_contrat_collaborateur = "//*[@id=\"formStep2\"]/div[3]/div[1]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Type_du_contrat_collaborateur_IL = "//*[@id=\"formStep2\"]/div[3]/div[1]/acc-select-cr/ng-select/div/input";
    public static final String Type_du_contrat_collaborateur_CL = "//*[@id=\"formStep2\"]/div[3]/div[1]/acc-select-cr/ng-select/div/ul/li";
    public static final String Enregistrer_Collaborateur = "//*[@id=\"step2\"]/div/app-core-rh-employee-add-popup-affectation/ul/li[2]/button";
    public static final String Email_collaborateur = "input[type='email']";
    public static final String Sauvegarder_Collaborateur = "i[title='Enregistrer']";
    public static final String Dossier_administratif_collaborateur = "//*[@id=\"cover\"]/ul[1]/li[2]";
    public static final String Ajouter_un_cycle_de_travail_collaborateur = "//*[@id=\"administrative\"]/div/acc-core-rh-employee-administrative-file-page/acc-core-rh-employee-work-cycle-form/acc-table/section/div[2]/ul/li[2]";
    public static final String Cycle_de_travail_collaborateur = "//*[@id=\"administrative\"]/div/acc-core-rh-employee-administrative-file-page/acc-core-rh-employee-work-cycle-form/acc-table/section/div[2]/div/form/div[1]/acc-table-form/div/div[1]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Cycle_de_travail_collaborateur_IL = "//*[@id=\"administrative\"]/div/acc-core-rh-employee-administrative-file-page/acc-core-rh-employee-work-cycle-form/acc-table/section/div[2]/div/form/div[1]/acc-table-form/div/div[1]/acc-select-cr/ng-select/div/input";
    public static final String Cycle_de_travail_collaborateur_CL = "div[class='ui-select-choices-row']";
    public static final String Première_semaine_collaborateur = "//*[@id=\"administrative\"]/div/acc-core-rh-employee-administrative-file-page/acc-core-rh-employee-work-cycle-form/acc-table/section/div[2]/div/form/div[1]/acc-table-form/div/div[2]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Première_semaine_collaborateur_IL = "//*[@id=\"administrative\"]/div/acc-core-rh-employee-administrative-file-page/acc-core-rh-employee-work-cycle-form/acc-table/section/div[2]/div/form/div[1]/acc-table-form/div/div[2]/acc-select-cr/ng-select/div/input";
    public static final String Première_semaine_collaborateur_CL = "//*[@id=\"administrative\"]/div/acc-core-rh-employee-administrative-file-page/acc-core-rh-employee-work-cycle-form/acc-table/section/div[2]/div/form/div[1]/acc-table-form/div/div[2]/acc-select-cr/ng-select/div/ul/li";
    public static final String Date_d_effet_collaborateur = "//*[@id=\"administrative\"]/div/acc-core-rh-employee-administrative-file-page/acc-core-rh-employee-work-cycle-form/acc-table/section/div[2]/div/form/div[1]/acc-table-form/div/div[3]/acc-date-picker/my-date-picker/div/div/input";
    public static final String Valider_cycle_de_travail_collaborateur = "//*[@id=\"administrative\"]/div/acc-core-rh-employee-administrative-file-page/acc-core-rh-employee-work-cycle-form/acc-table/section/div[2]/div/form/div[2]/button[2]";
    public static final String Rémunération_collaborateur = "//*[@id=\"cover\"]/ul[1]/li[3]";
    public static final String Ajouter_un_salaire_collaborateur = "//div[@id='remuneration']//div[2]//button[2]";
    public static final String Montant_collaborateur = "/html/body/app-root/app-layout/div/section/div/ng-component/div[1]/div/acc-core-rh-employee-form/form/div[2]/div[3]/div/acc-core-rh-employee-remuneration-file-page/acc-core-rh-employee-salary-form/acc-table/section/div[2]/div/form/div[1]/acc-table-form/div[1]/div[1]/input";
    public static final String Devise_collaborateur = "//*[@id=\"remuneration\"]/div/acc-core-rh-employee-remuneration-file-page/acc-core-rh-employee-salary-form/acc-table/section/div[2]/div/form/div[1]/acc-table-form/div[1]/div[2]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Devise_collaborateur_IL = "//*[@id=\"remuneration\"]/div/acc-core-rh-employee-remuneration-file-page/acc-core-rh-employee-salary-form/acc-table/section/div[2]/div/form/div[1]/acc-table-form/div[1]/div[2]/acc-select-cr/ng-select/div/input";
    public static final String Devise_collaborateur_CL = "//*[@id=\"remuneration\"]/div/acc-core-rh-employee-remuneration-file-page/acc-core-rh-employee-salary-form/acc-table/section/div[2]/div/form/div[1]/acc-table-form/div[1]/div[2]/acc-select-cr/ng-select/div/ul/li";
    public static final String Date_de_début_collaborateur = "//*[@id=\"remuneration\"]/div/acc-core-rh-employee-remuneration-file-page/acc-core-rh-employee-salary-form/acc-table/section/div[2]/div/form/div[1]/acc-table-form/div[2]/div[1]/acc-date-picker/my-date-picker/div/div/input";
    public static final String Valider_salaire_collaborateur = "//*[@id=\"remuneration\"]/div/acc-core-rh-employee-remuneration-file-page/acc-core-rh-employee-salary-form/acc-table/section/div[2]/div/form/div[2]/button[2]";
    public static final String Rechercher_Employe = "/html/body/app-root/app-layout/div/section/div/ng-component/header/div/div/input";
    public static final String DateDeNaissance_DossierIndividuel = "//*[@id=\"individuel\"]/div/acc-core-rh-employee-individual-file-page/acc-core-rh-employee-identity-form/section/div[2]/div/div[3]/div[1]/acc-date-picker/my-date-picker/div/div/input";
    public static final String DateDentree = "//*[@id=\"administrative\"]/div/acc-core-rh-employee-administrative-file-page/acc-core-rh-employee-hiring-exit-form/acc-table/section/div[2]/div/div/div/div/table/tbody/tr/td[1]/span";
    public static final String Date_Sortie_Collaborateur = "//*[@id=\"administrative\"]/div/acc-core-rh-employee-administrative-file-page/acc-core-rh-employee-hiring-exit-form/acc-table/section/div[2]/div/div/div/div/table/tbody/tr/td[4]";
    public static final String Bouton_Enregistrer_Modification = "//*[@id=\"data-view \"]/acc-core-rh-employee-form/form/acc-core-rh-referential-update-revert-actions/i[2]";
    public static final String DateDentree_DossierIndividuel = "//*[@id=\"administrative\"]/div/acc-core-rh-employee-administrative-file-page/acc-core-rh-employee-hiring-exit-form/acc-table/section/div[2]/div/form/div[1]/acc-table-form/div[1]/div[1]/acc-date-picker/my-date-picker/div/div/input";
    public static final String Bouton_Modifier_Entree_Sortie = "//*[@id=\"administrative\"]/div/acc-core-rh-employee-administrative-file-page/acc-core-rh-employee-hiring-exit-form/acc-table/section/div[2]/div/div/div/div/table/tbody/tr/td[6]/i";
    public static final String Bouton_Valider_Modification_Entree_Sortie = "//*[@id=\"administrative\"]/div/acc-core-rh-employee-administrative-file-page/acc-core-rh-employee-hiring-exit-form/acc-table/section/div[2]/div/form/div[2]/button[2]";
    public static final String Date_entree_texte = "//*[@id=\"administrative\"]/div/acc-core-rh-employee-administrative-file-page/acc-core-rh-employee-hiring-exit-form/acc-table/section/div[2]/div/div/div/div/table/tbody/tr/td[1]/span";
    public static final String NomUser = "//*[@id=\"cover\"]/div/h3";
    public static final String Fiche_User_Date_Entree = "//*[@id=\"cover\"]/ul[2]/li[3]/span/time";
    public static final String Recherche_Collaborateur = "/html/body/app-root/app-layout/div/section/div/ng-component/header/div/div/input";
    public static final String Liste_Collaborateurs = "/html/body/app-root/app-layout/div/section/div/ng-component/div[1]/app-acc-list/div/div/a";
    public static final String Onglet_Rénumération = "//*[@id=\"cover\"]/ul[1]/li[3]";
    public static final String Bouton_Ajouter_Affectation_Véhicule = "//div[@id='remuneration']//div[6]//button[2]";
    public static final String Liste_Immatriculation = "//*[@id=\"remuneration\"]/div/acc-core-rh-employee-remuneration-file-page/acc-core-rh-employee-function-vehicle-form/acc-table/section/div[2]/div/form/div[1]/acc-table-form/div[1]/div[1]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Liste_Immatriculation_IL = "//*[@id=\"remuneration\"]/div/acc-core-rh-employee-remuneration-file-page/acc-core-rh-employee-function-vehicle-form/acc-table/section/div[2]/div/form/div[1]/acc-table-form/div[1]/div[1]/acc-select-cr/ng-select/div/input";
    public static final String Liste_Immatriculation_CL = "//*[@id=\"remuneration\"]/div/acc-core-rh-employee-remuneration-file-page/acc-core-rh-employee-function-vehicle-form/acc-table/section/div[2]/div/form/div[1]/acc-table-form/div[1]/div[1]/acc-select-cr/ng-select/div/ul/li";
    public static final String Début_Usage_Véhicule = "//*[@id=\"remuneration\"]/div/acc-core-rh-employee-remuneration-file-page/acc-core-rh-employee-function-vehicle-form/acc-table/section/div[2]/div/form/div[1]/acc-table-form/div[2]/div[1]/acc-date-picker/my-date-picker/div/div/input";
    public static final String Fin_Usage_Véhicule = "//*[@id=\"remuneration\"]/div/acc-core-rh-employee-remuneration-file-page/acc-core-rh-employee-function-vehicle-form/acc-table/section/div[2]/div/form/div[1]/acc-table-form/div[2]/div[2]/acc-date-picker/my-date-picker/div/div/input";
    public static final String Bouton_Valider_Affecatation_Véhicule = "//*[@id=\"remuneration\"]/div/acc-core-rh-employee-remuneration-file-page/acc-core-rh-employee-function-vehicle-form/acc-table/section/div[2]/div/form/div[2]/button[2]";
    public static final String Bouton_Enregistrer_Gestion_Personnel = "//*[@id=\"data-view \"]/acc-core-rh-employee-form/form/acc-core-rh-referential-update-revert-actions/i[2]";
    public static final String Onglet_Dossier_Administratif = "//*[@id=\"cover\"]/ul[1]/li[2]";
    public static final String Bouton_Ajouter_Affectation = "/html[1]/body[1]/app-root[1]/app-layout[1]/div[1]/section[1]/div[1]/ng-component[1]/div[1]/div[1]/acc-core-rh-employee-form[1]/form[1]/div[2]/div[2]/div[1]/acc-core-rh-employee-administrative-file-page[1]/div[4]/button[2]";
    public static final String Date_Debut_Affectation = "//acc-date-picker[@name='affectationEffectiveDate']//my-date-picker//div//div//input";
    public static final String Entité_Affectation = "/html[1]/body[1]/ngb-modal-window[1]/div[1]/div[1]/acc-affectation-add[1]/div[1]/div[2]/section[1]/form[1]/div[2]/div[1]/acc-select-list[1]/ng-select[1]/div[1]/div[2]/span[1]";
    public static final String Entité_Affectation_IL = "/html[1]/body[1]/ngb-modal-window[1]/div[1]/div[1]/acc-affectation-add[1]/div[1]/div[2]/section[1]/form[1]/div[2]/div[1]/acc-select-list[1]/ng-select[1]/div[1]/input[1]";
        public static final String Entité_Affectation_CL = "//body//ngb-modal-window//li";
    public static final String Poste_Affectation = "/html[1]/body[1]/ngb-modal-window[1]/div[1]/div[1]/acc-affectation-add[1]/div[1]/div[2]/section[1]/form[1]/div[2]/div[3]/acc-select-list[1]/ng-select[1]/div[1]/div[2]/span[1]";
    public static final String Poste_Affectation_IL = "/html[1]/body[1]/ngb-modal-window[1]/div[1]/div[1]/acc-affectation-add[1]/div[1]/div[2]/section[1]/form[1]/div[2]/div[3]/acc-select-list[1]/ng-select[1]/div[1]/input[1]";
    public static final String Poste_Affectation_CL = "//body//ngb-modal-window//li";
    public static final String Bouton_Valider_Affectation = "//button[@class='btn btn-info']";
    public static final String Date_Entrée_Entrée_Sortie = "//acc-date-picker[@name='hiringEffectiveDate']//my-date-picker//div//div//input";
    public static final String Date_Sortie_Entrée_Sortie = "//acc-date-picker[@name='leaveDate']//my-date-picker//div//div//input";
    public static final String Icone_Modifier_Entrées_Sorties = "/html[1]/body[1]/app-root[1]/app-layout[1]/div[1]/section[1]/div[1]/ng-component[1]/div[1]/div[1]/acc-core-rh-employee-form[1]/form[1]/div[2]/div[2]/div[1]/acc-core-rh-employee-administrative-file-page[1]/div[2]/acc-hiring-exit-list[1]/div[1]/p-datatable[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[6]/span[2]/span[1]/i[1]";
    public static final String Motif_Sortie_Entrées_Sorties = "//span[contains(text(),'Sélectionner le motif de sortie')]";
    public static final String Motif_Sortie_Entrées_Sorties_IL = "//input[@placeholder='Sélectionner le motif de sortie']";
    public static final String Motif_Sortie_Entrées_Sorties_CL = "//ngb-modal-window[@class='modal fade show in']//li";
    public static final String Valider_Entrées_Sorties = "//button[@class='btn btn-info']";
    public static final String Status_Collaborateur = "//*[@id=\"cover\"]/ul[2]/li[3]/span";
    public static final String Recherche_KO = "//strong[@class='no-resut-match']";
    public static final String Filtre_Recherche_Collaborateur = "/html/body/app-root/app-layout/div/section/div/ng-component/header/div/div/label[2]";
    public static final String Statut_Filtre_Collaborateur = "/html[1]/body[1]/app-root[1]/app-layout[1]/div[1]/section[1]/div[1]/ng-component[1]/header[1]/div[1]/div[1]/div[1]/form[1]/div[3]/ng-select[1]/div[1]/div[2]/span[1]/span[1]";
    public static final String Statut_Filtre_Collaborateur_IL = "/html[1]/body[1]/app-root[1]/app-layout[1]/div[1]/section[1]/div[1]/ng-component[1]/header[1]/div[1]/div[1]/div[1]/form[1]/div[3]/ng-select[1]/div[1]/input";
    public static final String Statut_Filtre_Collaborateur_CL = "/html[1]/body[1]/app-root[1]/app-layout[1]/div[1]/section[1]/div[1]/ng-component[1]/header[1]/div[1]/div[1]/div[1]/form[1]/div[3]/ng-select[1]/div[1]/ul/li";
    public static final String Recherche_Filtre_Collaborateur = "/html[1]/body[1]/app-root[1]/app-layout[1]/div[1]/section[1]/div[1]/ng-component[1]/header[1]/div[1]/div[1]/div[1]/form[1]/div[14]/div[1]";
    public static final String Message_Erreur_Date_Sortie = "/html/body/ngb-modal-window/div/div/acc-hiring-exit-form/div/div[2]/section/form/div[2]/div[2]/div";
    public static final String JS_Icone_Suppression_Motif_Sortie = "//ngb-modal-window[@class='modal fade show in']//div[3]//acc-select-cr[1]//ng-select[1]//div[1]//div[2]//span[1]//a[1]";
    public static final String Icone_Suppression_Date_Sortie = "//acc-date-picker[@name='leaveDate']//button[1]";
    public static final String Autres_Paramètres = "/html/body/app-root/app-layout/div/section/div/acc-core-config-container/div/div[1]/div/div[2]/a[4]";
    public static final String JS_optiontest = "//input[@name='activateEchelon']";
    public static final String Onglet_SST = "//a[contains(@title,'Santé et sécurité au travail')]";
    public static final String Ajouter_Travailleur_Designe = "//div[@id='sst']//div[2]//button[2]";
    public static final String Diplome_Travailleur_Designe = "/html/body/ngb-modal-window/div/div/acc-designated-employee-add/div/div[2]/section/form/div/div[1]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Diplome_Travailleur_Designe_IL = "/html/body/ngb-modal-window/div/div/acc-designated-employee-add/div/div[2]/section/form/div/div[1]/acc-select-cr/ng-select/div/input";
    public static final String Diplome_Travailleur_Designe_CL = "/html/body/ngb-modal-window/div/div/acc-designated-employee-add/div/div[2]/section/form/div/div[1]/acc-select-cr/ng-select/div/ul/li";
    public static final String Categorie_Travailleur_Designe = "/html/body/ngb-modal-window/div/div/acc-designated-employee-add/div/div[2]/section/form/div/div[2]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Categorie_Travailleur_Designe_IL = "/html/body/ngb-modal-window/div/div/acc-designated-employee-add/div/div[2]/section/form/div/div[2]/acc-select-cr/ng-select/div/input";
    public static final String Categorie_Travailleur_Designe_CL = "/html/body/ngb-modal-window/div/div/acc-designated-employee-add/div/div[2]/section/form/div/div[2]/acc-select-cr/ng-select/div/ul/li";
    public static final String Date_Obtention = "/html/body/ngb-modal-window/div/div/acc-designated-employee-add/div/div[2]/section/form/div/div[3]/acc-date-picker/my-date-picker/div/div/input";
    public static final String Date_Recyclage = "/html/body/ngb-modal-window/div/div/acc-designated-employee-add/div/div[2]/section/form/div/div[4]/acc-date-picker/my-date-picker/div/div/input";
    public static final String Valider_Travailleur_Designe = "//button[@class='btn btn-info']";
    public static final String Date_De_Naissance = "//*[@id=\"individuel\"]/div/acc-core-rh-employee-individual-file-page/acc-core-rh-employee-identity-form/section/div[2]/div/div[3]/div[1]/acc-date-picker/my-date-picker/div/div/input";
    public static final String Ajouter_Saveteur_Secouriste = "//div[@id='sst']//div[4]//button[2]";
    public static final String Diplome_Sauveteur_Secouriste = "/html/body/ngb-modal-window/div/div/acc-stt-rescuer-add/div/div[2]/section/form/div/div[1]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Diplome_Sauveteur_Secouriste_IL = "/html/body/ngb-modal-window/div/div/acc-stt-rescuer-add/div/div[2]/section/form/div/div[1]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Diplome_Sauveteur_Secouriste_CL = "/html/body/ngb-modal-window/div/div/acc-stt-rescuer-add/div/div[2]/section/form/div/div[1]/acc-select-cr/ng-select/div/ul/li";
    public static final String Date_Obtention_Sauveteur_Secouriste = "/html/body/ngb-modal-window/div/div/acc-stt-rescuer-add/div/div[2]/section/form/div/div[2]/acc-date-picker/my-date-picker/div/div/input";
    public static final String Date_Recyclage_Sauveteur_Secouriste = "/html/body/ngb-modal-window/div/div/acc-stt-rescuer-add/div/div[2]/section/form/div/div[3]/acc-date-picker/my-date-picker/div/div/input";
    public static final String JS_Occuper_Poste_Saveuteur_Secouriste = "//div[@class='checkbox col-sm-4 ui-disabled']//span[@class='check']";
    public static final String Valider_Saveuteur_Secouriste = "//button[@class='btn btn-info']";
    public static final String Ajouter_Equipier_Premiere_Intervention = "//div[@id='sst']//div[6]//button[2]";
    public static final String Diplome_Equipier_Premiere_Intervention = "/html/body/ngb-modal-window/div/div/acc-stt-first-aid-add/div/div[2]/section/form/div/div[1]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Diplome_Equipier_Premiere_Intervention_IL = "/html/body/ngb-modal-window/div/div/acc-stt-first-aid-add/div/div[2]/section/form/div/div[1]/acc-select-cr/ng-select/div/input";
    public static final String Diplome_Equipier_Premiere_Intervention_CL = "/html/body/ngb-modal-window/div/div/acc-stt-first-aid-add/div/div[2]/section/form/div/div[1]/acc-select-cr/ng-select/div/ul/li";
    public static final String DateObtention_Equipier_Premiere_Intervention = "/html/body/ngb-modal-window/div/div/acc-stt-first-aid-add/div/div[2]/section/form/div/div[2]/acc-date-picker/my-date-picker/div/div/input";
    public static final String JS_Occuper_Poste_Equipier_Premiere_Intervention = "/html/body/ngb-modal-window/div/div/acc-stt-first-aid-add/div/div[2]/section/form/div/div[4]/div/label/span/span";
    public static final String Valider_Equipier_Premiere_Intervention = "//button[@class='btn btn-info']";
    public static final String DateRecyclage_Equipier_Premiere_Intervention = "/html/body/ngb-modal-window/div/div/acc-stt-first-aid-add/div/div[2]/section/form/div/div[3]/acc-date-picker/my-date-picker/div/div/input";
    public static final String Ajouter_Personnel_GuideFile_SerreFile = "//div[@id='sst']//div[8]//button[2]";
    public static final String Diplome_Personnel_GuideFile_SerreFile = "/html/body/ngb-modal-window/div/div/acc-stt-guide-employee-add/div/div[2]/section/form/div/div[1]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Diplome_Personnel_GuideFile_SerreFile_IL = "/html/body/ngb-modal-window/div/div/acc-stt-guide-employee-add/div/div[2]/section/form/div/div[1]/acc-select-cr/ng-select/div/input";
    public static final String Diplome_Personnel_GuideFile_SerreFile_CL = "/html/body/ngb-modal-window/div/div/acc-stt-guide-employee-add/div/div[2]/section/form/div/div[1]/acc-select-cr/ng-select/div/ul/li";
    public static final String Type_Personnel_GuideFile_SerreFile = "/html/body/ngb-modal-window/div/div/acc-stt-guide-employee-add/div/div[2]/section/form/div/div[2]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Type_Personnel_GuideFile_SerreFile_IL = "/html/body/ngb-modal-window/div/div/acc-stt-guide-employee-add/div/div[2]/section/form/div/div[2]/acc-select-cr/ng-select/div/input";
    public static final String Type_Personnel_GuideFile_SerreFile_CL = "/html/body/ngb-modal-window/div/div/acc-stt-guide-employee-add/div/div[2]/section/form/div/div[2]/acc-select-cr/ng-select/div/ul/li";
    public static final String Valider_Personnel_GuideFile_SerreFile = "//button[@class='btn btn-info']";
    public static final String DateObtention_Personnel_GuideFile_SerreFile = "/html/body/ngb-modal-window/div/div/acc-stt-guide-employee-add/div/div[2]/section/form/div/div[3]/acc-date-picker/my-date-picker/div/div/input";
    public static final String DateRecyclage_Personnel_GuideFile_SerreFile = "/html/body/ngb-modal-window/div/div/acc-stt-guide-employee-add/div/div[2]/section/form/div/div[4]/acc-date-picker/my-date-picker/div/div/input";
    public static final String Bouton_Modifier_Travailleur_Designe_SST = "//*[@id=\"sst\"]/acc-core-rh-employee-stt-form/div[2]/acc-designated-employee-list/div/p-datatable/div/div[1]/table/tbody/tr/td[6]/span[2]/span/i";


}
