package com.QA.locators;

public class RecrutementLocators {


    public static final String Demande_De_Recrutement = "/html/body/app-root/app-layout/div/section/div/acc-global-container/acc-portal-container/div/div/div[1]/acc-left-side-container/div/acc-user-widget/div/div[3]/div/div[2]/ul/li[4]/a";
    public static final String Ajout_Demande_rec_mgr = "/html/body/app-root/app-layout/div/section/div/acc-global-container/acc-talent-component/ng-component/div/div/acc-portal-talent-manager-recruitment-offers-container/div[2]/div[1]/button";
    public static final String Intitule_dmd_rec_mgr = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[1]/div[2]/div[1]/div[1]/input";
    public static final String Effectif_a_couvrir_dmd_rec_mgr = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[1]/div[2]/div[1]/div[2]/input";
    public static final String Cible_dmd_rec_mgr = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[1]/div[2]/div[2]/div[1]/acc-select-cr/ng-select/div/input";
    public static final String Cible_dmd_rec_mgr_IL = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[1]/div[2]/div[2]/div[1]/acc-select-cr/ng-select/div/input";
    public static final String Cible_dmd_rec_mgr_CL = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[1]/div[2]/div[2]/div[1]/acc-select-cr/ng-select/div/ul/li/div/a/div";
    public static final String Lieu_dmd_rec_mgr = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[1]/div[2]/div[2]/div[2]/acc-select-cr/ng-select/div/input";
    public static final String Lieu_dmd_rec_mgr_IL = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[1]/div[2]/div[2]/div[2]/acc-select-cr/ng-select/div/input";
    public static final String Lieu_dmd_rec_mgr_CL = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[1]/div[2]/div[2]/div[2]/acc-select-cr/ng-select/div/ul/li/div/a/div";
    public static final String Contrat_dmd_rec_mgr = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[1]/div[2]/div[2]/div[3]/acc-select-cr/ng-select/div/input";
    public static final String Contrat_dmd_rec_mgr_IL = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[1]/div[2]/div[2]/div[3]/acc-select-cr/ng-select/div/input";
    public static final String Contrat_dmd_rec_mgr_CL = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[1]/div[2]/div[2]/div[3]/acc-select-cr/ng-select/div/ul/li/div/a/div";
    public static final String Emploi_associe_dmd_rec_mgr = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[1]/div[2]/div[3]/div[1]/ss-multiselect-dropdown/div/button";
    public static final String Emploi_associe_dmd_rec_mgr_IL = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[1]/div[2]/div[3]/div[1]/ss-multiselect-dropdown/div/ul/li[1]/div/input";
    public static final String Emploi_associe_dmd_rec_mgr_CL = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[1]/div[2]/div[3]/div[1]/ss-multiselect-dropdown/div/ul/li[3]";
    public static final String Poste_associe_dmd_rec_mgr = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[1]/div[2]/div[3]/div[2]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Poste_associe_dmd_rec_mgr_IL = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[1]/div[2]/div[3]/div[2]/acc-select-cr/ng-select/div/input";
    public static final String Poste_associe_dmd_rec_mgr_CL = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[1]/div[2]/div[3]/div[2]/acc-select-cr/ng-select/div/ul/li/div/a/div";
    public static final String Mission_dmd_rec_mgr = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[1]/div[2]/div[4]/div/p-editor/div/div[2]/div[1]";
    public static final String Profil_Atouts_dmd_rec_mgr = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[1]/div[2]/div[5]/div/p-editor/div/div[2]/div[1]";
    public static final String Justification_dmd_rec_mgr = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[1]/div[2]/div[6]/div/textarea";
    public static final String Upload_Document_Recrutement = "//*[@id=\"hide\"]/label/input";
    public static final String Devise_dmd_rec_mgr = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[3]/div[2]/div/div[1]/acc-select-cr/ng-select/div/div[2]/span";
    public static final String Devise_dmd_rec_mgr_IL = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[3]/div[2]/div/div[1]/acc-select-cr/ng-select/div/input";
    public static final String Devise_dmd_rec_mgr_CL = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[3]/div[2]/div/div[1]/acc-select-cr/ng-select/div/ul/li/div/a/div";
    public static final String Salaire_dmd_rec_mgr = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[3]/div[2]/div/div[2]/input";
    public static final String salaire_annuel_demande_rec = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[3]/div[2]/div/div[5]/div";
    public static final String Bonus_dmd_rec_mgr = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[3]/div[2]/div/div[3]/input";
    public static final String Autres_dmd_rec_mgr = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[3]/div[2]/div/div[4]/input";
    public static final String Budgetise_dmd_rec_mgr = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[3]/div[2]/div/div[6]/div/div/label/span";
    public static final String Budget_dmd_rec_mgr = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[3]/div[2]/div/div[6]/div[2]/div/input";
    public static final String montant_demande_rec = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[2]/div/acc-portal-talent-manager-recruitment-offers-form/form/section[3]/div[2]/div/div[6]/div[2]/div[2]";
    public static final String Envoyer_dmd_rec_mgr = "/html/body/ngb-modal-window/div/div/acc-portal-talent-manager-recruitment-offers-modal/div[3]/button";
    public static final String libelle_demandes_rec_mgr = "//*[@id=\"ngb-tab-0-panel\"]/div/acc-portal-talent-manager-recruitment-offers-table/p-datatable/div/div[1]/div/div[2]/div/table/tbody/tr[1]/td[2]/span[2]/span";
    public static final String creation_demandes_rec_mgr = "//*[@id=\"ngb-tab-0-panel\"]/div/acc-portal-talent-manager-recruitment-offers-table/p-datatable/div/div[1]/div/div[2]/div/table/tbody/tr[1]/td[3]/span[2]/span";
    public static final String couvrir_demandes_rec_mgr = "//*[@id=\"ngb-tab-0-panel\"]/div/acc-portal-talent-manager-recruitment-offers-table/p-datatable/div/div[1]/div/div[2]/div/table/tbody/tr[1]/td[5]/span[2]/span";
    public static final String lieu_demandes_rec_mgr = "//*[@id=\"ngb-tab-0-panel\"]/div/acc-portal-talent-manager-recruitment-offers-table/p-datatable/div/div[1]/div/div[2]/div/table/tbody/tr[1]/td[6]/span[2]/span";
    public static final String publiee_demandes_rec_mgr = "//*[@id=\"ngb-tab-0-panel\"]/div/acc-portal-talent-manager-recruitment-offers-table/p-datatable/div/div[1]/div/div[2]/div/table/tbody/tr[1]/td[7]";


}
