package com.QA.locators;

public class TimelineLocators {

    public static final String Champ_Statut = "publish-clickId";
    public static final String Champ_Input_Statut = "//*[@id=\"timeline\"]/acc-timeline-publish/div/div[1]/acc-mention-per-timelines/quill-editor/div/div[1]";
    public static final String Liste_Deroulante_Timeline_Image = "/html/body/ngb-modal-window/div/div/acc-publish-modal/div/div[1]/fieldset/div/ng-select/div/div[2]";
    public static final String Liste_Deroulante_Timeline_Image_IL = "//*[@id=\"timeline\"]/acc-timeline-publish/div/div[2]/div/ng-select/div/input";
    public static final String Liste_Deroulante_Timeline_Image_CL = "/html/body/ngb-modal-window/div/div/acc-publish-modal/div/div[1]/fieldset/div/ng-select/div/ul/li";
    public static final String Liste_Deroulante_Timeline = "//*[@id=\"timeline\"]/acc-timeline-publish/div/div[2]/div[2]/ng-select/div/div[2]";
    public static final String Liste_Deroulante_Timeline_IL = "//*[@id=\"timeline\"]/acc-timeline-publish/div/div[2]/div/ng-select/div/input";
    public static final String Liste_Deroulante_Timeline_CL = "//*[@id=\"timeline\"]/acc-timeline-publish/div/div[2]/div[2]/ng-select/div/ul/li";
    public static final String Liste_Deroulante_Timeline_Video="/html/body/ngb-modal-window/div/div/acc-publish-modal/div/div[1]/fieldset/div/ng-select/div/div[2]";
    public static final String Liste_Deroulante_Timeline_Video_IL="/html/body/ngb-modal-window/div/div/acc-publish-modal/div/div[1]/fieldset/div/ng-select/div/input";
    public static final String Liste_Deroulante_Timeline_Video_CL="/html/body/ngb-modal-window/div/div/acc-publish-modal/div/div[1]/fieldset/div/ng-select/div/ul/li";
    public static final String Premiere_Timeline_liste = "//*[@id=\"timeline\"]/acc-timeline-publish/div/div[2]/div/ng-select/div/ul/li[2]/div/a/div";
    public static final String Bouton_Publication_Statut = "//*[@id=\"timeline\"]/acc-timeline-publish/div/div[2]/button";
    public static final String Premiere_Publication_Timeline = "//*[@id=\"post-holder\"]/acc-timeline-post/div/div[3]";
    public static final String Bouton_Menu_Modif_Supp_Statut = "//*[@id=\"post-holder\"]/acc-timeline-post/div/div[2]" ;
    public static final String Bouton_Modif_Statut = "//*[@id=\"post-holder\"]/acc-timeline-post/div/div[2]/ul/li[1]";
    public static final String Champ_Input_Modification_Statut ="//div[@class='ql-editor']";
    public static final String Bouton_Publier_Statut = "//button[@class='btn btn-primary pull-right share-button btn-edit']";
    public static final String Bouton_Supprimer_Statut = "//*[@id=\"post-holder\"]/acc-timeline-post/div/div[2]/ul/li[2]";
    public static final String Bouton_Valider_Suppression_Statut = ".mb-sm:nth-child(2)";
    public static final String Champs_Input_Commentaire = "//*[@id=\"post-holder\"]/acc-timeline-post/div/acc-timeline-post-comments/div/div/div/form/div/acc-mention-per-timelines/quill-editor/div/div[1]";
    public static final String JS_Bouton_Submit_Commentaire = "//*[@id=\"post-holder\"]/acc-timeline-post/div/acc-timeline-post-comments/div/div/div/form/button";
    public static final String Bouton_Affichage_Commentaires_Existant = "//*[@id=\"post-holder\"]/acc-timeline-post/div/div[3]/div[1]/a[2]";
    public static final String Contenu_Commentaire_avec_TAG = "//*[@id=\"post-holder\"]/acc-timeline-post/div/acc-timeline-post-comments/div/div[2]/div/div/div/div[2]/span[1]/p/span/span/span/a";
    public static final String Champ_Input_Image_Publication="checkedinput";
    public static final String Champ_Input_Video_Publication="checkedinputVid";
    public static final String Bloc_Publication_TimeLine="div[class='padder mb sharing-share-box--is-unfocused parent-publish-div']";
    public static final String Champ_Input_Document_Publication="checkedinputdoc";
    public static final String Bouton_Publication_Video="/html/body/ngb-modal-window/div/div/acc-publish-modal/div/div[1]/fieldset/button[1]";
    public static final String Champ_Input_Statut_Video="/html/body/ngb-modal-window/div/div/acc-publish-modal/div/div[1]/fieldset/acc-mention-per-timelines/quill-editor/div/div[1]";
    public static final String Premiere_Publication_TimeLine_Statut="//*[@id=\"post-holder\"]/acc-timeline-post/div/div[3]/acc-timeline-post-status/div/div";
    public static final String Premiere_Video_Publier_Timeline="/html/body/app-root/app-layout/div/section/div/acc-global-container/acc-portal-container/div/div/div[2]/div[2]/acc-timeline-container/div/div[1]/div/acc-timeline-post/div/div[3]/acc-video-player/div/vg-player/video";
    public static final String Champ_Input_Piece_Jointe_Publication="checkedinputdoc";
    public static final String Bouton_Publication_Piece_Jointe="/html/body/ngb-modal-window/div/div/acc-publish-modal/div/fieldset/button[1]";
    public static final String Champ_Input_Album_Publication = "albumHeader";
    public static final String JS_Bouton_Publication_Album="/html/body/ngb-modal-window/div/div/acc-publish-modal/div/div[1]/fieldset/button[1]";
    public static final String Prmier_Album_Afficher_Photo="div[class='img-level-2 media-object user_picture pointer col-md-6 height-level-0']";
    public static final String Premiere_Image_Publier_Timeline="/html/body/app-root/app-layout/div/section/div/acc-global-container/acc-portal-container/div/div/div[2]/div[2]/acc-timeline-container/div/div[1]/div/acc-timeline-post/div";
    public static final String Premiere_Image_Publier_Timeline_Afficher="img[class='singleFotoPoste cursor']";
    public static final String Bouton_Publication_Image="/html/body/ngb-modal-window/div/div/acc-publish-modal/div/div[1]/fieldset/button[1]";
    public static final String Container_Premiere_Publication="div[class='poste-single']";
    public static final String Champ_Input_Statut_Image="/html/body/ngb-modal-window/div/div/acc-publish-modal/div/div[1]/fieldset/acc-mention-per-timelines/quill-editor/div/div[1]";
    public static final String Premiere_Pulication_Statut="#post-holder > acc-timeline-post > div > div.div-cell > acc-timeline-post-status > div > div > p > span";
    public static final String Premiere_Publication_Timeline_Notification = "//*[@id=\"post-holder\"]/acc-timeline-post/div/div[2]/acc-timeline-post-status/div/div";
    public static final String Champ_Input_Album_Publication_Image_2 = "/html/body/ngb-modal-window/div/div/acc-publish-modal/div/div[2]/div[2]/div/input";
}
